#pragma once

typedef enum
{
    LIBBANIO_CMD_INIT,
    LIBBANIO_CMD_DEINIT,

    LIBBANIO_CMD_GET_VERSION,
//    LIBBANIO_CMD_GET_ERRNO,
    LIBBANIO_CMD_GET_OS,

    LIBBANIO_CMD_FOPEN,
    LIBBANIO_CMD_FCLOSE,
    LIBBANIO_CMD_FREAD,
    LIBBANIO_CMD_FWRITE,
    LIBBANIO_CMD_FSEEK,
    LIBBANIO_CMD_FTELL,
    LIBBANIO_CMD_UNLINK,

    LIBBANIO_CMD_OPENDIR,
    LIBBANIO_CMD_CLOSEDIR,
    LIBBANIO_CMD_READDIR,

} LIBBANIO_CMD;

typedef enum
{
    LIBBANIO_OS_UNKNOWN = 0,
    LIBBANIO_OS_LINUX,
    LIBBANIO_OS_MAC,
    LIBBANIO_OS_WINDOWS,
} LIBBANIO_OS;
